---
- hosts: vbox
  remote_user: ubuntu
  sudo: yes
  
  tasks:

  - name: Get the QGIS repository key    
    apt_key: keyserver=keyserver.ubuntu.com id=073D307A618E5811 state=present
    retries: 3
    
  - name: Add the QGIS repository  
    apt_repository: repo="deb http://qgis.org/debian xenial main" state=present

  - name: Add the CRAN repository key  
    apt_key: keyserver=keyserver.ubuntu.com id=E084DAB9 
    retries: 3
    
  - name: Add the CRAN repository  
    apt_repository: repo="deb https://cran.r-project.org/bin/linux/ubuntu/ xenial main" state=present

#  - name: Add the graph-tool repository key  
#    apt_key: keyserver=pgp.skewed.de id=612DEFB798507F25
#    retries: 3
    
#  - name: Add the graph-tool repository
#    apt_repository: repo="deb http://downloads.skewed.de/apt/xenial xenial universe" state=present
    
# https://github.com/ansible/ansible-modules-core/issues/2951

  - name: Update and upgrade apt packages
    apt: update_cache=yes
    retries: 3
    ignore_errors: yes
    register: apt_result
    until: apt_result|success

  - name: retry if needed using command apt-get update
    command: apt-get update
    when: apt_result|failed
    ignore_errors: yes

  - name: Install some utilities
    apt: name={{item}} state=installed
    with_items:
    - wget
    - curl
    - screen
    - git
    
  - name: Install Python package dependencies
    apt: name={{item}} state=installed
    with_items:
    - build-essential
    - python3-dev
    - python3-pip
    - python-setuptools
    - gfortran
    - gfortran-4.8
    - libblas-dev
    - libblas3
    - liblapack-dev
    - liblapack3
    - libopenblas-base
    - libcurl4-openssl-dev
    - python-pycurl
    - python-dev
    - python-pip
    - libxft-dev 
    - libpng-dev
    - libfreetype6-dev
    - pkg-config
    - virtualenv
    - python-igraph
    - libssl-dev

#    - python3-graph-tool
    
  - name: Install Python packages
    pip: executable=pip3 name={{item}}
    with_items:
    - Jinja2
    - PyGithub
    - PyYAML    
    - bs4
    - charade
    - chardet
    - cluster
    - envoy
    - facebook-sdk   
    - feedparser
    - flask
    - folium
    - gensim
    - geopy
    - google-api-python-client
    - httplib2
    - ipyparallel
    - jupyter
    - lda
    - lxml
    - matplotlib
    - networkx
    - nltk
    - numpy
    - oauthlib
    - pandas
    - prettytable
    - pyemd
    - pyldavis
    - pyparsing
    - python-dateutil
    - python-gflags
    - python-linkedin
    - python-rake
    - python-twitter
    - pytz
    - pyzmq
    - readability-lxml
    - requests
    - requests-oauthlib
    - scikit-learn
    - scipy
    - Scrapy
    - seaborn
    - six
    - tagme
    - twitter
    - twitter-text-py
    - twython
    - unicodecsv
    - vaderSentiment
    - wheel
      
  - name: Install QuantumGIS
    apt: name={{item}} state=installed
    with_items:
    - qgis
    - python-qgis
    - qgis-plugin-grass
    
  - name: Install Spyder
    apt: name=spyder state=installed

  - name: Install R
    apt: name=r-base state=installed    

#  - name: Install Rstudio LaTeX dependencies
#    apt: name={{item}} state=installed
#    with_items:    
#    - texlive-latex-base
#    - texlive-fonts-recommended
#    - texlive-fonts-extra
#    - texlive-latex-extra
#    - texinfo    
    
  - name: Install Rstudio
    apt: deb=https://download1.rstudio.org/rstudio-1.0.136-amd64.deb
    
  - name: Install R package dependencies
    apt: name={{item}} state=installed
    with_items:
    - libjpeg-turbo8-dev
    - libgsl2
    - libgsl-dev
    - libxml2-dev
    - libzmq3-dev
    
#  - name: Install Rstudio-Server
#    apt: deb=https://download2.rstudio.org/rstudio-server-1.0.136-amd64.deb
    
  - name: Install R packages
    cran: name={{item}} state=present
    with_items:
    - devtools
    - httr
    - RCurl
    - plyr
    - rjson
    - stringr
    - reshape2
    - ggplot2
    - scales
    - crayon
    - pbdZMQ
    
  - name: Get ngramr 1.4.5
    get_url: url=https://cran.r-project.org/src/contrib/Archive/ngramr/ngramr_1.4.5.tar.gz dest=/ngramr_1.4.5.tar.gz
    
  - name: Install ngramr
    command: R CMD INSTALL /ngramr_1.4.5.tar.gz
      
  - name: Get slam 1.37
    get_url: url=http://cran.r-project.org/src/contrib/Archive/slam/slam_0.1-37.tar.gz dest=/slam_0.1-37.tar.gz
 
  - name: Install slam
    command: R CMD INSTALL /slam_0.1-37.tar.gz
    
  - name: Install R Jupyter kernel
    command: R -e "devtools::install_github('IRkernel/IRkernel')"

  - name: Install the kernel system-wide
    command: R -e "IRkernel::installspec(user = FALSE)"    
    
  - name: Install more R packages
    cran: name={{item}} state=present
    with_items:
    - NeuralNetTools
    - RColorBrewer
    - RedditExtractoR
    - Rfacebook
    - XML
    - arules
    - catdata
    - cluster
    - corrplot 
    - dplyr
    - ggmap
    - ggvis
    - googleVis
    - h2o
    - igraph
    - jpeg
    - jsonlite
    - magrittr
    - maps
    - nnet
    - recommenderlab
    - rpart
    - rworldmap
    - shiny
    - swirl
    - tm
    - topicmodels
    - twitteR
    - wordcloud
    - repr
    - IRdisplay
    - crayon
    - pbdZMQ
    - devtools
    - lubridate
    - rmarkdown
    - caTools
    - knitr
   
  - name: Configure Lightdm
    copy: src=/lightdm.conf dest=/etc/lightdm/lightdm.conf.d/lightdm.conf mode=0555
    
  - name: Copy desktop files
    copy: src="{{ item }}" dest=/home/ubuntu/Desktop/ mode=0755 owner=ubuntu group=ubuntu
    with_fileglob:
    - /icons/*
    
  - name: Run Jupyter on boot
    copy: src=/rc.local dest=/etc/rc.local
    
  - name: Swirl course directory
    file: path=/home/ubuntu/swirlcourses owner=ubuntu state=directory
  
  - name: Swirl data directory
    file: path=/home/ubuntu/swirldata owner=ubuntu state=directory
  
  - name: Configure .Rprofile
    copy: src=/.Rprofile dest=/home/ubuntu/.Rprofile mode=0644 owner=ubuntu group=ubuntu
    
  - name: Tutorials directory
    file: path=/home/ubuntu/tutorials owner=ubuntu state=directory
    
  - name: Get the RAKE tutorial
    git: repo=https://github.com/zelandiya/RAKE-tutorial.git dest=/home/ubuntu/tutorials/RAKE-tutorial

  - name: Get DistrictDataLabs intro to NLTK
    git: repo=https://github.com/DistrictDataLabs/intro-to-nltk dest=/home/ubuntu/tutorials/intro-to-nltk  

  - name: Get DistrictDataLabs intro Scikit-Learn
    git: repo=https://github.com/DistrictDataLabs/machine-learning dest=/home/ubuntu/tutorials/machine-learning     
  
  - name: Get Folgert Karsdorp's Python course
    git: repo=https://github.com/fbkarsdorp/python-course dest=/home/ubuntu/tutorials/python-course
  
  - name: Give the user ownership of the tutorials directory
    file: path=/home/ubuntu/tutorials owner=ubuntu group=ubuntu recurse=yes
    
  - name: apt-get clean
    command: apt-get clean    
    
